/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderBar: typeof import('./src/components/bar/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMailOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconMailOutline']
    MenuBar: typeof import('./src/components/bar/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YkAvatar: typeof import('@yike-design/ui')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui')['YkBadge']
    YkButton: typeof import('@yike-design/ui')['YkButton']
    YkRate: typeof import('@yike-design/ui')['YkRate']
    YkSpace: typeof import('@yike-design/ui')['YkSpace']
    YkText: typeof import('@yike-design/ui')['YkText']
    YkTheme: typeof import('@yike-design/ui')['YkTheme']
  }
}
